<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Kartheekslaptop" name="webdriverpractice.userInteractions.UserInteractionsExercisesTest" tests="5" failures="1" timestamp="2020-06-06T11:29:31 IST" time="6.051" errors="0">
  <testcase name="dragAndDropDraggable2ToDroppable1" time="0.928" classname="webdriverpractice.userInteractions.UserInteractionsExercisesTest"/>
  <system-out/>
  <testcase name="ControlSpace" time="3.058" classname="webdriverpractice.userInteractions.UserInteractionsExercisesTest">
    <failure type="java.lang.AssertionError" message="expected [Let GO!!] but found [Drop Here]">
      <![CDATA[java.lang.AssertionError: expected [Let GO!!] but found [Drop Here]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at webdriverpractice.userInteractions.UserInteractionsExercisesTest.ControlSpace(UserInteractionsExercisesTest.java:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ControlSpace -->
  <system-out/>
  <testcase name="moveDraggable1ToDroppable1" time="0.960" classname="webdriverpractice.userInteractions.UserInteractionsExercisesTest"/>
  <system-out/>
  <testcase name="ControlB" time="0.460" classname="webdriverpractice.userInteractions.UserInteractionsExercisesTest"/>
  <system-out/>
  <testcase name="drawOnCanvas" time="0.645" classname="webdriverpractice.userInteractions.UserInteractionsExercisesTest"/>
  <system-out/>
</testsuite> <!-- webdriverpractice.userInteractions.UserInteractionsExercisesTest -->
